name: BeyondVotes
main: Lihad.BeyondVotes.BeyondVotes
version: 6.0
commands:
  bv:
    description: Invalid Command
    usage: Invalid Command
  bvset:
    description: Invalid Command
    usage: Invalid Command
  bvdelete:
    description: Invalid Command
    usage: Invalid Command
  bvreload:
    description: Invalid Command
    usage: Invalid Command
  bvoverride:
    description: Invalid Command
    usage: Invalid Command
  ivoted:
    description: Invalid Command
    usage: Invalid Command